### ISSUE TITLE
Where do I get data.json content?

### ISSUE THREAD

**Issue by tomasruud** [slang800/tumblr-theme-parser#9]
Do I manually have to generate all the preview data, or is there somewhere I can download my existing content?

**Comment by notslang** [comment]
You can grab it from `https://www.tumblr.com/customize_api/demo_content/<name of blog>`. I got that URL from looking at the requests made in the "Edit Theme" page (`https://www.tumblr.com/customize/<name of blog>`) so it's probably the JSON structure that Tumblr uses internally.

You'll need to be logged in to reach that page, but once you are, you can get the content for any blog. For example: https://www.tumblr.com/customize_api/demo_content/booksofadam or https://www.tumblr.com/customize_api/demo_content/nasa make pretty good filler content.

PS: this should probably be added to the readme.

**Comment by tomasruud** [comment]
Nice man! Do you want me to make a pull request, or do you just add it yourself?

**Comment by notslang** [comment]
Sure, a PR would be great :smile:. Also, feel free to close this issue - I don't own the repo anymore, so I can't do it on my own.
